# Generated by Django 6.0.8 on 2026-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Shree Akhil Bharatiya Kutch Kadva Patidar Sanatan Samaj Kheralu Ayojit Saraswati Sanman Samaroh', help_text='Full name of the event', max_length=500)),
                ('academic_year', models.CharField(db_index=True, help_text='Academic year (e.g., 2026-27)', max_length=10, unique=True)),
                ('event_date', models.DateField(blank=True, help_text='Date when the ceremony will be held', null=True)),
                ('registration_start_date', models.DateField(blank=True, help_text='When registrations open', null=True)),
                ('registration_end_date', models.DateField(blank=True, help_text='When registrations close', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Registration'), ('closed', 'Closed')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-academic_year'],
            },
        ),
    ]
