services:
  - type: web
    name: community-management-system
    env: python
    buildCommand: python -m pip install --upgrade pip && python -m pip install --no-cache-dir -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
