# Generated by Django 6.0.8 on 2026-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated permanent Family ID (e.g., FAM-00001)', max_length=10, unique=True)),
                ('family_name', models.CharField(db_index=True, help_text='Family or firm name', max_length=255)),
                ('responsible_person_name', models.CharField(help_text='Name of the responsible person (head of family)', max_length=255)),
                ('mobile_number', models.CharField(db_index=True, help_text='Primary mobile number', max_length=15)),
                ('village_city', models.CharField(db_index=True, help_text='Village or city name', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive families are hidden from public but data is preserved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['family_id'],
            },
        ),
    ]
