# Generated by Django 6.0.8 on 2026-09-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated permanent Student ID (e.g., STU-00001)', max_length=10, unique=True)),
                ('full_name', models.CharField(db_index=True, help_text='Full name of the student', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive students are hidden from public but data is preserved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(help_text='The family this student belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='families.family')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_id'],
            },
        ),
    ]
