# Generated by Django 6.0.8 on 2026-09-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the award category (e.g., Academic Excellence)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the award category')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden but preserved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Award Category',
                'verbose_name_plural': 'Award Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional remarks about this award')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_registration', models.ForeignKey(help_text='The annual registration this award is for.', on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='registrations.annualregistration')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='awards.awardcategory')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('annual_registration', 'category'), name='unique_award_per_registration_category')],
            },
        ),
    ]
