# Generated by Django 6.0.8 on 2026-09-23 06:06

import apps.registrations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(db_index=True, help_text='Standard/Class (e.g., 10, 11, 12, B.Com Sem-1)', max_length=50)),
                ('medium', models.CharField(choices=[('gujarati', 'Gujarati'), ('english', 'English'), ('hindi', 'Hindi')], db_index=True, help_text='Medium of instruction', max_length=20)),
                ('percentage_or_cgpa', models.DecimalField(decimal_places=2, help_text='Percentage or CGPA obtained', max_digits=6)),
                ('special_achievement', models.TextField(blank=True, default='', help_text='Any special achievements or awards (optional)')),
                ('result_document', models.FileField(blank=True, help_text='Upload result document (PDF, JPG, PNG — max 5MB)', null=True, upload_to=apps.registrations.models.result_document_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=15)),
                ('admin_remarks', models.TextField(blank=True, default='', help_text='Remarks by admin during verification')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_registrations', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annual Registration',
                'verbose_name_plural': 'Annual Registrations',
                'ordering': ['-event__academic_year', 'student__student_id'],
                'indexes': [models.Index(fields=['student', 'event'], name='registratio_student_9b3402_idx'), models.Index(fields=['event', 'status'], name='registratio_event_i_8b1d8a_idx'), models.Index(fields=['event', 'standard'], name='registratio_event_i_9ed440_idx'), models.Index(fields=['event', 'medium'], name='registratio_event_i_36bc1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'event'), name='unique_student_event_registration')],
            },
        ),
    ]
