# Generated by Django 6.0.7 on 2026-09-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualregistration',
            name='institution_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College')], db_index=True, default='school', help_text='Whether the student is in School or College', max_length=10),
            preserve_default=False,
        ),
    ]
